/**
 * @file ZoomVideoSDKMaskHelper.h
 * @brief Interface for video mask operations including applying and managing video masks with various shapes and configurations.
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <ZoomVideoSDK/ZoomVideoSDKConstants.h>

/**
 * @class ZoomVideoSDKMaskInfo
 * @brief The mask info to generate the mask bitmap.
 */
@interface ZoomVideoSDKMaskInfo : NSObject

@property (nonatomic, assign) ZoomVideoSDKMaskShape shape;
/**
 * @brief The left margin. For rectangle and oval.
 */
@property (nonatomic, assign) CGFloat left;

/**
 * @brief The top margin. For rectangle and oval.
 */
@property (nonatomic, assign) CGFloat top;

/**
 * @brief The right margin. For rectangle and oval.
 */
@property (nonatomic, assign) CGFloat right;

/**
 * @brief The bottom margin. For rectangle and oval.
 */
@property (nonatomic, assign) CGFloat bottom;

/**
 * @brief The x-coordinate of the center of the circle to be drawn.
 */
@property (nonatomic, assign) CGFloat cx;

/**
 * @brief The y-coordinate of the center of the circle to be drawn.
 */
@property (nonatomic, assign) CGFloat cy;

/**
 * @brief The radius of the circle to be drawn.
 */
@property (nonatomic, assign) CGFloat radius;

@end

/**
 * @class ZoomVideoSDKMaskHelper
 * @brief The helper to set the video mask.
 */
@interface ZoomVideoSDKMaskHelper: NSObject

/**
 * @brief Generates a mask UIImage based on the mask information that is located within the canvas width or the canvas height. The recommended aspect ratio is 1280 * 720 or 720 * 1280.
 * @param maskInfos The mask information used to generate mask.
 * @param canvasWidth The canvas width used to locate the mask information.
 * @param canvasHeight The canvas height used to locate the mask information.
 * @return If the function succeeds, it returns the mask UIImage. Otherwise, this function fails and returns nil.
 */
- (UIImage * _Nullable)generateMask:(NSArray <ZoomVideoSDKMaskInfo *> * _Nullable)maskInfos width:(NSInteger)canvasWidth height:(NSInteger)canvasHeight;

/**
 * @brief Sets the mask to self video.
 * @param maskImage UIImage generated by interface generateMask:width:height:. Or you can generate the bitmap by yourself. This mask image should meet the following conditions: The area through which you want to see the video should be set to opaque and the other areas should be set to transparent.
 * @param backgroundImage The background image.
 * @param isMirrored Whether the video that is based on the mask generated is mirrored. For \link ZoomVideoSDKVideoCanvas \endlink, the value \link ZoomVideoSDKVideoHelper::isMyVideoMirrored \endlink can be passed in. For \link ZoomVideoSDKRawDataPipe \endlink, the correct value should be passed.
 * @return If the function succeeds, it returns Errors_Success. Otherwise, this function returns an error.
 */
- (ZoomVideoSDKError)setVideoMask:(UIImage * _Nullable)maskImage background:(UIImage * _Nullable)backgroundImage mirror:(BOOL)isMirrored;
@end


