#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef ZMUITOOLKIT_SWIFT_H
#define ZMUITOOLKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import ReplayKit;
@import UIKit;
@import ZoomVideoSDK;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZMUIToolkit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class ZoomVideoSDKUserHelper;
@class ZoomVideoSDKUser;
@class ZoomVideoSDKVideoHelper;
@class ZoomVideoSDKAudioHelper;
@class ZoomVideoSDKShareHelper;
@class ZoomVideoSDKShareAction;
@class UIView;
@class ZoomVideoSDKLiveStreamHelper;
@class ZoomVideoSDKIncomingLiveStreamHelper;
@class ZoomVideoSDKIncomingLiveStreamStatus;
@class ZoomVideoSDKChatHelper;
@class ZoomVideoSDKChatMessage;
@class ZoomVideoSDKAudioRawData;
@class ZoomVideoSDKAudioDevice;
@class ZoomVideoSDKRecordAgreementHandler;
@class ZoomVideoSDKRawDataPipe;
@class ZoomVideoSDKVideoCanvas;
@class ZoomVideoSDKProxySettingHandler;
@class ZoomVideoSDKSSLCertificateInfo;
@class ZoomVideoSDKLiveTranscriptionMessageInfo;
@class ZoomVideoSDKLiveTranscriptionLanguage;
@class ZoomVideoSDKAnnotationHelper;
@class ZoomVideoSDKSendFile;
@class ZoomVideoSDKReceiveFile;
@class ZoomVideoSDKSubSessionKit;
@class ZoomVideoSDKSubSessionManager;
@class ZoomVideoSDKSubSessionParticipant;
@class ZoomVideoSDKSubSessionUserHelpRequestHandler;
@class ZoomVideoSDKWhiteboardHelper;
/// Forwards <code>ZoomVideoSDKDelegate</code> callbacks to weakly-held child delegates.
SWIFT_CLASS_NAMED("CompositeZoomVideoSDKDelegate")
@interface ZMUICompositeZoomVideoSDKDelegate : NSObject <ZoomVideoSDKDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)addDelegate:(id <ZoomVideoSDKDelegate> _Nonnull)delegate;
- (void)removeDelegate:(id <ZoomVideoSDKDelegate> _Nonnull)delegate;
- (void)onSessionJoin;
- (void)onSessionLeave:(ZoomVideoSDKSessionLeaveReason)reason;
- (void)onError:(ZoomVideoSDKError)ErrorType detail:(NSInteger)details;
- (void)onSessionNeedPassword:(ZoomVideoSDKError (^ _Nullable)(NSString * _Nullable, BOOL))completion;
- (void)onSessionPasswordWrong:(ZoomVideoSDKError (^ _Nullable)(NSString * _Nullable, BOOL))completion;
- (void)onUserJoin:(ZoomVideoSDKUserHelper * _Nullable)helper users:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onUserLeave:(ZoomVideoSDKUserHelper * _Nullable)helper users:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onUserVideoStatusChanged:(ZoomVideoSDKVideoHelper * _Nullable)helper user:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onUserAudioStatusChanged:(ZoomVideoSDKAudioHelper * _Nullable)helper user:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onUserActiveAudioChanged:(ZoomVideoSDKUserHelper * _Nullable)helper users:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onUserHostChanged:(ZoomVideoSDKUserHelper * _Nullable)helper users:(ZoomVideoSDKUser * _Nullable)user;
- (void)onUserManagerChanged:(ZoomVideoSDKUser * _Nullable)user;
- (void)onUserNameChanged:(ZoomVideoSDKUser * _Nullable)user;
- (void)onUserShareStatusChanged:(ZoomVideoSDKShareHelper * _Nullable)helper user:(ZoomVideoSDKUser * _Nullable)user shareAction:(ZoomVideoSDKShareAction * _Nullable)shareAction;
- (void)onFailedToStartShare:(ZoomVideoSDKShareHelper * _Nonnull)helper user:(ZoomVideoSDKUser * _Nullable)user;
- (void)onShareSettingChanged:(ZoomVideoSDKShareSetting)setting;
- (void)onShareContentChanged:(ZoomVideoSDKShareHelper * _Nullable)shareHelper user:(ZoomVideoSDKUser * _Nullable)user shareAction:(ZoomVideoSDKShareAction * _Nullable)shareAction;
- (void)onShareCaptureSizeChanged:(ZoomVideoSDKShareHelper * _Nullable)shareHelper user:(ZoomVideoSDKUser * _Nullable)user shareAction:(ZoomVideoSDKShareAction * _Nullable)shareAction;
- (void)onShareContentSizeChanged:(ZoomVideoSDKShareHelper * _Nullable)helper user:(ZoomVideoSDKUser * _Nullable)user shareAction:(ZoomVideoSDKShareAction * _Nullable)shareAction;
- (void)onShareCanvasSubscribeFailWithUser:(ZoomVideoSDKUser * _Nullable)user view:(UIView * _Nullable)view shareAction:(ZoomVideoSDKShareAction * _Nullable)shareAction;
- (void)onLiveStreamStatusChanged:(ZoomVideoSDKLiveStreamHelper * _Nullable)helper status:(ZoomVideoSDKLiveStreamStatus)status;
- (void)onBindIncomingLiveStreamResponse:(ZoomVideoSDKIncomingLiveStreamHelper * _Nullable)helper success:(BOOL)success streamKeyID:(NSString * _Nullable)streamKeyID;
- (void)onUnbindIncomingLiveStreamResponse:(ZoomVideoSDKIncomingLiveStreamHelper * _Nullable)helper success:(BOOL)success streamKeyID:(NSString * _Nullable)streamKeyID;
- (void)onIncomingLiveStreamStatusResponse:(ZoomVideoSDKIncomingLiveStreamHelper * _Nullable)helper success:(BOOL)success streamsStatusList:(NSArray<ZoomVideoSDKIncomingLiveStreamStatus *> * _Nullable)streamsStatusList;
- (void)onStartIncomingLiveStreamResponse:(ZoomVideoSDKIncomingLiveStreamHelper * _Nullable)helper success:(BOOL)success streamKeyID:(NSString * _Nullable)streamKeyID;
- (void)onStopIncomingLiveStreamResponse:(ZoomVideoSDKIncomingLiveStreamHelper * _Nullable)helper success:(BOOL)success streamKeyID:(NSString * _Nullable)streamKeyID;
- (void)onStartBroadcastResponse:(BOOL)isSuccess channelID:(NSString * _Nonnull)channelID;
- (void)onStopBroadcastResponse:(BOOL)isSuccess;
- (void)onGetBroadcastControlStatus:(BOOL)isSuccess status:(ZoomVideoSDKBroadcastControlStatus)status;
- (void)onStreamingJoinStatusChanged:(ZoomVideoSDKStreamingJoinStatus)status;
- (void)onChatPrivilegeChanged:(ZoomVideoSDKChatHelper * _Nullable)helper privilege:(ZoomVideoSDKChatPrivilegeType)currentPrivilege;
- (void)onChatNewMessageNotify:(ZoomVideoSDKChatHelper * _Nullable)helper message:(ZoomVideoSDKChatMessage * _Nullable)chatMessage;
- (void)onChatMsgDeleteNotification:(ZoomVideoSDKChatHelper * _Nullable)helper messageID:(NSString * _Nonnull)msgID deleteBy:(ZoomVideoSDKChatMsgDeleteBy)type;
- (void)onMixedAudioRawDataReceived:(ZoomVideoSDKAudioRawData * _Nullable)rawData;
- (void)onOneWayAudioRawDataReceived:(ZoomVideoSDKAudioRawData * _Nullable)rawData user:(ZoomVideoSDKUser * _Nullable)user;
- (void)onSharedAudioRawDataReceived:(ZoomVideoSDKAudioRawData * _Nullable)rawData;
- (void)onAudioLevelChanged:(NSUInteger)level audioSharing:(BOOL)bAudioSharing user:(ZoomVideoSDKUser * _Nullable)user;
- (void)onMyAudioSourceTypeChanged:(ZoomVideoSDKAudioDevice * _Nullable)device;
- (void)onInviteByPhoneStatus:(ZoomVideoSDKPhoneStatus)status failReason:(ZoomVideoSDKPhoneFailedReason)failReason;
- (void)onCalloutJoinSuccess:(ZoomVideoSDKUser * _Nullable)user phoneNumber:(NSString * _Nullable)phoneNumber;
- (void)onCallCRCDeviceStatusChanged:(ZoomVideoSDKCRCCallStatus)state;
- (void)onCmdChannelConnectResult:(BOOL)success;
- (void)onCommandReceived:(NSString * _Nullable)commandContent sendUser:(ZoomVideoSDKUser * _Nullable)sender;
- (void)onCameraControlRequestResult:(ZoomVideoSDKUser * _Nullable)user approved:(BOOL)isApproved;
- (void)onCloudRecordingStatus:(ZoomVideoSDKRecordingStatus)status recordAgreementHandler:(ZoomVideoSDKRecordAgreementHandler * _Nullable)handler;
- (void)onUserRecordAgreementNotification:(ZoomVideoSDKUser * _Nullable)user;
- (void)onHostAskUnmute;
- (void)onTestMicStatusChanged:(ZoomVideoSDKTestMicStatus)status;
- (void)onMicSpeakerVolumeChanged:(int32_t)micVolume speakerVolume:(int32_t)speakerVolume;
- (void)onMultiCameraStreamStatusChanged:(ZoomVideoSDKMultiCameraStreamStatus)status parentUser:(ZoomVideoSDKUser * _Nullable)user videoPipe:(ZoomVideoSDKRawDataPipe * _Nullable)videoPipe;
- (void)onMultiCameraStreamStatusChanged:(ZoomVideoSDKMultiCameraStreamStatus)status parentUser:(ZoomVideoSDKUser * _Nullable)user videoCanvas:(ZoomVideoSDKVideoCanvas * _Nullable)videoCanvas;
- (void)onSystemPermissionRequired:(ZoomVideoSDKSystemPermissionType)permissionType;
- (void)onProxySettingNotification:(ZoomVideoSDKProxySettingHandler * _Nonnull)handler;
- (void)onSSLCertVerifiedFailNotification:(ZoomVideoSDKSSLCertificateInfo * _Nonnull)handler;
- (void)onLiveTranscriptionStatus:(ZoomVideoSDKLiveTranscriptionStatus)status;
- (void)onLiveTranscriptionMsgReceived:(ZoomVideoSDKLiveTranscriptionMessageInfo * _Nullable)messageInfo;
- (void)onOriginalLanguageMsgReceived:(ZoomVideoSDKLiveTranscriptionMessageInfo * _Nullable)messageInfo;
- (void)onLiveTranscriptionMsgError:(ZoomVideoSDKLiveTranscriptionLanguage * _Nullable)spokenLanguage transLanguage:(ZoomVideoSDKLiveTranscriptionLanguage * _Nullable)transcriptLanguage;
- (void)onSpokenLanguageChanged:(ZoomVideoSDKLiveTranscriptionLanguage * _Nullable)spokenLanguage;
- (void)onUserNetworkStatusChanged:(ZoomVideoSDKDataType)type level:(ZoomVideoSDKNetworkStatus)level user:(ZoomVideoSDKUser * _Nullable)user;
- (void)onUserOverallNetworkStatusChanged:(ZoomVideoSDKNetworkStatus)level user:(ZoomVideoSDKUser * _Nullable)user;
- (void)onUserVideoNetworkStatusChanged:(ZoomVideoSDKNetworkStatus)status user:(ZoomVideoSDKUser * _Nullable)user;
- (void)onAnnotationHelperCleanUp:(ZoomVideoSDKAnnotationHelper * _Nullable)helper;
- (void)onAnnotationPrivilegeChangeWithUser:(ZoomVideoSDKUser * _Nullable)user shareAction:(ZoomVideoSDKShareAction * _Nullable)shareAction;
- (void)onAnnotationToolTypeChanged:(ZoomVideoSDKAnnotationHelper * _Nullable)helper view:(UIView * _Nullable)view toolType:(ZoomVideoSDKAnnotationToolType)toolType;
- (void)onVideoCanvasSubscribeFail:(ZoomVideoSDKSubscribeFailReason)failReason user:(ZoomVideoSDKUser * _Nullable)user view:(UIView * _Nullable)view;
- (void)onSendFileStatus:(ZoomVideoSDKSendFile * _Nullable)file status:(ZoomVideoSDKFileTransferStatus)status;
- (void)onReceiveFileStatus:(ZoomVideoSDKReceiveFile * _Nullable)file status:(ZoomVideoSDKFileTransferStatus)status;
- (void)onVideoAlphaChannelStatusChanged:(BOOL)isAlphaChannelOn;
- (void)onSpotlightVideoChanged:(ZoomVideoSDKVideoHelper * _Nullable)videoHelper userList:(NSArray<ZoomVideoSDKUser *> * _Nullable)userList;
- (void)onUVCCameraStatusChange:(ZoomVideoSDKUVCCameraStatus)status;
- (void)onSubSessionStatusChanged:(ZoomVideoSDKSubSessionStatus)status subSession:(NSArray<ZoomVideoSDKSubSessionKit *> * _Nonnull)pSubSessionKitList;
- (void)onSubSessionManagerHandle:(ZoomVideoSDKSubSessionManager * _Nullable)pManager;
- (void)onSubSessionParticipantHandle:(ZoomVideoSDKSubSessionParticipant * _Nullable)pParticipant;
- (void)onSubSessionUsersUpdate:(ZoomVideoSDKSubSessionKit * _Nonnull)pSubSessionKit;
- (void)onBroadcastMessageFromMainSession:(NSString * _Nonnull)sMessage userName:(NSString * _Nonnull)sUserName;
- (void)onSubSessionUserHelpRequestHandler:(ZoomVideoSDKSubSessionUserHelpRequestHandler * _Nonnull)pHandler;
- (void)onSubSessionUserHelpRequestResult:(ZoomVideoSDKUserHelpRequestResult)result;
- (void)onInAppScreenShareErrorCode:(RPRecordingErrorCode)code;
- (void)onInAppScreenShareAvailableChanged:(BOOL)available;
- (void)onUserWhiteboardShareStatusChanged:(ZoomVideoSDKUser * _Nonnull)user whiteboardhelper:(ZoomVideoSDKWhiteboardHelper * _Nonnull)whiteboardHelper;
- (void)onCanvasSnapshotTaken:(ZoomVideoSDKUser * _Nonnull)user isShare:(BOOL)isShare;
- (void)onCanvasSnapshotIncompatible:(ZoomVideoSDKUser * _Nonnull)user;
- (void)onRealTimeMediaStreamsStatus:(ZoomVideoSDKRealTimeMediaStreamsStatus)status;
- (void)onRealTimeMediaStreamsFail:(ZoomVideoSDKRealTimeMediaStreamsFailReason)failReason;
@end

@class ZoomVideoSDK;
/// Holds the host’s <code>ZoomVideoSDK</code> instance and the toolkit’s fan-out delegate.
/// <code>initialize(...)</code> and <code>cleanup()</code> are <code>@MainActor</code> so the SDK reference is
/// only ever mutated from main; reads are unconstrained and assumed to come
/// from main-thread UIKit code paths (the storage is <code>nonisolated(unsafe)</code>).
SWIFT_CLASS_NAMED("ZMUIToolKitManager")
@interface ZMUIToolKitManager : NSObject
/// Controls whether participants are shown the blocking cloud-recording
/// consent dialog when a recording starts. When set to <code>false</code>, the dialog
/// is suppressed (consent is auto-accepted) and a non-blocking “Recording
/// started” toast is shown instead. Defaults to <code>true</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL cloudRecordingConsentDialogEnabled;)
+ (BOOL)cloudRecordingConsentDialogEnabled SWIFT_WARN_UNUSED_RESULT;
+ (void)setCloudRecordingConsentDialogEnabled:(BOOL)newValue;
/// Fan-out delegate installed onto <code>ZoomVideoSDK.delegate</code> by <code>initialize</code>.
/// Register observers with <code>add(_:)</code> instead of assigning the SDK delegate
/// directly. Child delegates are held weakly.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZMUICompositeZoomVideoSDKDelegate * _Nonnull videoSDKDelegate;)
+ (ZMUICompositeZoomVideoSDKDelegate * _Nonnull)videoSDKDelegate SWIFT_WARN_UNUSED_RESULT;
/// SDK instance set by <code>initialize(...)</code>; <code>nil</code> after <code>cleanup()</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZoomVideoSDK * _Nullable videoSDK;)
+ (ZoomVideoSDK * _Nullable)videoSDK SWIFT_WARN_UNUSED_RESULT;
/// Connects the toolkit to the host’s <code>ZoomVideoSDK</code> instance and takes
/// ownership of its <code>delegate</code> slot. Callers must observe events via
/// <code>videoSDKDelegate.add(_:)</code>, not by reassigning <code>ZoomVideoSDK.delegate</code>.
/// Pair with <code>cleanup()</code> before tearing the SDK down.
+ (BOOL)initializeWithVideoSDK:(ZoomVideoSDK * _Nonnull)videoSDK bundleId:(NSString * _Nullable)bundleId SWIFT_WARN_UNUSED_RESULT;
/// Releases the SDK reference and clears the delegate slot if we still own
/// it. Registered child delegates on <code>videoSDKDelegate</code> are kept (weakly)
/// so listeners survive across re-initialization. Picture-in-Picture
/// subscriptions are released here because they hold an SDK delegate
/// callback that must not outlive the session.
+ (void)cleanup;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class NSCoder;
@class UITraitCollection;
@class UITouch;
@class UIEvent;
@class UIImage;
@class NSAttributedString;
SWIFT_CLASS_NAMED("ZMUIToolkitIconBtn")
@interface ZMUIToolkitIconBtn : UIButton
@property (nonatomic) BOOL showBadgeBackground;
@property (nonatomic, strong) UIColor * _Nullable badgeTextColor;
@property (nonatomic) CGFloat badgeWidth;
@property (nonatomic, strong) UIColor * _Nullable badgeBackgroundColor;
@property (nonatomic, copy) NSString * _Nullable badgeText;
@property (nonatomic) BOOL showBadge;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection SWIFT_AVAILABILITY(ios,deprecated=17.0,message="Use registerForTraitChanges instead");
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic, getter=isSelected) BOOL selected;
@property (nonatomic, getter=isEnabled) BOOL enabled;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)setImage:(UIImage * _Nullable)image forState:(UIControlState)state;
- (void)setTitle:(NSString * _Nullable)title forState:(UIControlState)state;
- (void)setAttributedTitle:(NSAttributedString * _Nullable)title forState:(UIControlState)state;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)layoutSubviews;
/// Override to handle button click events.
- (void)onButtonClicked;
/// Sets the background color of the button.
- (void)setBackgroundColorWithColor:(UIColor * _Nonnull)color;
/// Sets the corner radius of the button.
- (void)setRadiusWithRadius:(CGFloat)radius;
/// Sets the size of the button (width and height).
- (void)setSizeWithSize:(CGSize)size;
/// Sets the position of the button (frame.origin).
- (void)setPositionWithX:(CGFloat)x y:(CGFloat)y;
/// Sets the icon/tint color of the button.
- (void)setIconColorWithColor:(UIColor * _Nonnull)color;
/// Sets the icon image of the button.
- (void)setIconWithIcon:(UIImage * _Nonnull)icon;
/// Sets the size of the icon image. Pass <code>.zero</code> to fall back to intrinsic size.
- (void)setIconSize:(CGSize)size;
/// Sets the padding around the icon.
- (void)setIconPaddingWithPadding:(CGFloat)padding;
/// Sets the accessibility label and hint.
- (void)setAccessibilityWithLabel:(NSString * _Nullable)label hint:(NSString * _Nullable)hint;
/// Sets the button text/title.
- (void)setButtonText:(NSString * _Nullable)title;
/// Sets the text color of the button (used by sample).
- (void)setTextColor:(UIColor * _Nonnull)color;
/// Sets the font size of the button text (used by sample as <code>setTextFontSize</code>).
- (void)setTextFontSize:(CGFloat)fontSize;
/// Sets the spacing between icon and text (used by sample).
- (void)setTextSpacing:(CGFloat)spacing;
/// Sets the font size of the button text.
- (void)setFontSize:(CGFloat)fontSize;
/// Sets the font weight of the button text (Objective-C compatible).
/// 0.0 = ultraLight, 0.2 = thin, 0.3 = light, 0.4 = regular, 0.5 = medium,
/// 0.6 = semibold, 0.7 = bold, 0.8 = heavy, 1.0 = black.
- (void)setFontWeightRawValue:(CGFloat)weightValue;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS_NAMED("ZMUIToolkitAudioBtn")
@interface ZMUIToolkitAudioBtn : ZMUIToolkitIconBtn <ZoomVideoSDKDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)new;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)didMoveToWindow;
- (void)onSessionJoin;
- (void)onUserAudioStatusChanged:(ZoomVideoSDKAudioHelper * _Nullable)helper user:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
@end

SWIFT_CLASS_NAMED("ZMUIToolkitLeaveSessionBtn")
@interface ZMUIToolkitLeaveSessionBtn : ZMUIToolkitIconBtn
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)new;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("ZMUIToolkitMoreBtn")
@interface ZMUIToolkitMoreBtn : ZMUIToolkitIconBtn
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)new;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("ZMUIToolkitParticipantsBtn")
@interface ZMUIToolkitParticipantsBtn : ZMUIToolkitIconBtn <ZoomVideoSDKDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)new;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)onSessionJoin;
- (void)onSessionLeave:(ZoomVideoSDKSessionLeaveReason)reason;
- (void)onUserJoin:(ZoomVideoSDKUserHelper * _Nullable)helper users:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onUserLeave:(ZoomVideoSDKUserHelper * _Nullable)helper users:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
@end

SWIFT_CLASS_NAMED("ZMUIToolkitPauseShareBtn")
@interface ZMUIToolkitPauseShareBtn : ZMUIToolkitIconBtn <ZoomVideoSDKDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)new;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)didMoveToWindow;
- (void)onUserShareStatusChanged:(ZoomVideoSDKShareHelper * _Nullable)helper user:(ZoomVideoSDKUser * _Nullable)user shareAction:(ZoomVideoSDKShareAction * _Nullable)shareAction;
@end

SWIFT_CLASS_NAMED("ZMUIToolkitRootVideoView")
@interface ZMUIToolkitRootVideoView : UIView <ZoomVideoSDKDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)onUserJoin:(ZoomVideoSDKUserHelper * _Nullable)helper users:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onUserLeave:(ZoomVideoSDKUserHelper * _Nullable)helper users:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onSessionLeave:(ZoomVideoSDKSessionLeaveReason)reason;
- (void)onUserAudioStatusChanged:(ZoomVideoSDKAudioHelper * _Nullable)helper user:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onUserActiveAudioChanged:(ZoomVideoSDKUserHelper * _Nullable)helper users:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onUserVideoStatusChanged:(ZoomVideoSDKVideoHelper * _Nullable)helper user:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
- (void)onUserNameChanged:(ZoomVideoSDKUser * _Nullable)user;
- (void)onVideoCanvasSubscribeFail:(ZoomVideoSDKSubscribeFailReason)failReason user:(ZoomVideoSDKUser * _Nullable)user view:(UIView * _Nullable)view;
- (void)onUserVideoNetworkStatusChanged:(ZoomVideoSDKNetworkStatus)status user:(ZoomVideoSDKUser * _Nullable)user;
- (void)onSessionJoin;
- (void)setPositionWithX:(NSInteger)x y:(NSInteger)y;
- (void)setSizeWithWidth:(NSInteger)width height:(NSInteger)height;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)onUserShareStatusChanged:(ZoomVideoSDKShareHelper * _Nullable)helper user:(ZoomVideoSDKUser * _Nullable)user shareAction:(ZoomVideoSDKShareAction * _Nullable)shareAction;
- (void)onCloudRecordingStatus:(ZoomVideoSDKRecordingStatus)status recordAgreementHandler:(ZoomVideoSDKRecordAgreementHandler * _Nullable)handler;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIGestureRecognizer;
@interface ZMUIToolkitRootVideoView (SWIFT_EXTENSION(ZMUIToolkit)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

@class UIScrollView;
@interface ZMUIToolkitRootVideoView (SWIFT_EXTENSION(ZMUIToolkit)) <UIScrollViewDelegate>
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end

SWIFT_CLASS_NAMED("ZMUIToolkitShareBtn")
@interface ZMUIToolkitShareBtn : ZMUIToolkitIconBtn <ZoomVideoSDKDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)new;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)onUserShareStatusChanged:(ZoomVideoSDKShareHelper * _Nullable)helper user:(ZoomVideoSDKUser * _Nullable)user shareAction:(ZoomVideoSDKShareAction * _Nullable)shareAction;
@end

SWIFT_CLASS_NAMED("ZMUIToolkitVideoBtn")
@interface ZMUIToolkitVideoBtn : ZMUIToolkitIconBtn <ZoomVideoSDKDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)new;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)didMoveToWindow;
- (void)onSessionJoin;
- (void)onUserVideoStatusChanged:(ZoomVideoSDKVideoHelper * _Nullable)helper user:(NSArray<ZoomVideoSDKUser *> * _Nullable)users;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
